// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stage_parser;

namespace stage_parser.Migrations
{
    [DbContext(typeof(OfferContext))]
    [Migration("20190806070749_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("stage_parser.Offer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Floor_type");

                    b.Property<int>("Multilevel_floor");

                    b.Property<string>("description");

                    b.Property<string>("floor_is_last");

                    b.Property<int>("floor_level");

                    b.Property<int>("raw_floor_level");

                    b.Property<string>("source");

                    b.Property<string>("url");

                    b.Property<string>("uuid");

                    b.HasKey("id");

                    b.ToTable("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
